# Generated by Django 6.0.4 on 2026-04-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_cadalalum_cadmap_pimbarangayboundary_pimenlargement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RptReportCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='dashboard_rpt', max_length=50, unique=True)),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmvRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=100)),
                ('class_key', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=50)),
                ('unit_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('area_rrw', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['barangay', 'class_key'], name='maps_smvrat_baranga_10c314_idx'), models.Index(fields=['pin'], name='maps_smvrat_pin_02fac6_idx')],
                'unique_together': {('barangay', 'class_key', 'pin')},
            },
        ),
    ]
